# Uncomment the next line to define a global platform for your project
 platform :ios, '13.5'

target 'Food_Inc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealMiester
  # add pods for desired Firebase products
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  project '/Users/andrewthomas/Docs/MealMeister/Food_Project_Inc/Food_Inc.xcodeproj'
end
