# Uncomment the next line to define a global platform for your project
  platform :ios, '13.5'

target 'MealMeister' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealMeister
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'MealMeisterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealMeisterUITests' do
    # Pods for testing
  end

end
